import { registerAs } from '@nestjs/config';
export default registerAs('app', () => ({
  ENV: process.env.APP_ENV,
  PORT: process.env.APP_PORT,
  VERSION: process.env.APP_VERSION,
  SECRET_CODE: process.env.SECRET_CODE,
  SECRET_CODE_REFRESH: process.env.SECRET_CODE_REFRESH,
  TOPUP_CODE: process.env.TOPUP_CODE,
  URL_PUSH: process.env.URL_PUSH,
  NAME_PROGRAM: process.env.NAME_PROGRAM,
  PROGRAM_ID: process.env.PROGRAM_ID,
  KEYWORD: process.env.KEYWORD,
  JWT_SECRET: process.env.JWT_SECRET,
  JWT_EXPIRATION_TIME: process.env.JWT_EXPIRATION_TIME,
  COOKIES_EXPIRATION_DAY: process.env.COOKIES_EXPIRATION_DAY,
  API_PUSH_WA: process.env.API_PUSH_WA,
  DOMAIN_APP: process.env.DOMAIN_APP,
  CRYPTO_SECRET: process.env.CRYPTO_SECRET,
  TOKEN_FIREBASE: process.env.TOKEN_FIREBASE,
  MAIL_HOST: process.env.MAIL_HOST,
  MAIL_PORT: process.env.MAIL_PORT,
  MAIL_USER: process.env.MAIL_USER,
  MAIL_PASS: process.env.MAIL_PASS,
  HP_WA: process.env.HP_WA,
  BASE_URL: process.env.BASE_URL,
}));
